### ISSUE TITLE
There is no code in the repo for me.

### ISSUE THREAD

**Issue by blockhead48** [pterodactyl/mobile-addon#3]
I am not able to see any code for the mobile module / extension. Am I looking at the wrong thing or?

**Comment by Software-Noob** [comment]
It's not open-source, you can install the module for 0.7x from here: https://pterodactyl.cloud/login

There's no support for 1.x at this time yet, it's expected to hopefully be released in a few months.

**Comment by blockhead48** [comment]
Ahh ok. Thanks for clarifying that for me.
